version: '3'
services:
  server:
    container_name: postgrest
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://<USER>:<PASSWORD>@<HOST>:<PORT>/<DATABASE>
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_SERVER_PROXY_URI: http://SOME_SITE:3000 # This makes swagger call the right endpoint
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: "http://SOME_SITE:3000" # same as PGRST_SERVER_PROXY_URI