version: '3'
services:
  server:
    container_name: postgrest
    image: postgrest/postgrest
    ports:
      - "3030:3000"
    env_file:
      - ./envs/postgrest.env
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8090:8080"
    expose:
      - "8090"
    env_file:
      - ./envs/swagger.env
  flask:
    build: .
    container_name: api_wrapper
    ports:
      - "5000:5000"