version: "3.5"
services:
  tegola:
    container_name: tegola
    image: gospatial/tegola
    env_file: 
      - ./.env
    command: serve --config https://frederiksberg.github.io/tegola/config.toml
    networks:
      - front-facing
    restart: unless-stopped
  
  maputnik:
    container_name: maputnik
    image: maputnik/editor:latest
    networks:
      - front-facing
    depends_on:
      - tegola
    restart: unless-stopped
    
networks:
  front-facing:
    external: true
    name: proxy