version: '3.5'
services:
  th1:
    container_name: tilehut1
    image: frbsc/tilehut:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - tiles:/opt/tilehut/data:ro
    networks:
      - front-facing
    restart: unless-stopped

  th2:
    container_name: tilehut2
    image: frbsc/tilehut:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - tiles:/opt/tilehut/data:ro
    networks:
      - front-facing
    restart: unless-stopped

  th3:
    container_name: tilehut3
    image: frbsc/tilehut:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - tiles:/opt/tilehut/data:ro
    networks:
      - front-facing
    restart: unless-stopped

  ftp:
    container_name: th-ftp
    image: atmoz/sftp:latest
    volumes:
      - tiles:/home/gis/tiles:rw
      - ./pub_keys:/home/gis/.ssh/keys:ro
      - ./host_keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./host_keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./fixownership.sh:/etc/sftp.d/fixownership.sh
    ports:
      - "2222:22"
    command: gis::::tiles
    depends_on:
      - th1
      - th2
      - th3
    restart: unless-stopped
  
  th-landing:
    container_name: tilehut-landing
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./landing:/usr/share/nginx/html:rw
    depends_on: [ ftp ]
    networks:
      - front-facing

volumes:
  tiles:

networks:
  front-facing:
    external: true
    name: proxy
