version: '3.5'
services:
  nodered:
    image: nodered/node-red-docker
    volumes:
      - ./nodered:/data:rw
    networks:
      - front-facing
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana
    env_file:
      - ./.env
    user: "104"
    volumes:
      - ./grafana:/var/lib/grafana:rw
    networks:
      - front-facing
    restart: unless-stopped

networks:
  front-facing:
    external: true
    name: proxy