version: '3.5'
services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./confs:/etc/nginx/conf.d:rw
    networks:
      - proxy
    ports:
      - 80:80
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: proxy
